# Generated by Django 5.2 on 2025-05-07 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_given', models.DateField()),
                ('purpose', models.CharField(max_length=200)),
                ('amount_settled', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SETTLED', 'Settled'), ('PARTIALLY_SETTLED', 'Partially Settled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='management.driver')),
            ],
            options={
                'verbose_name': 'Driver Advance',
                'verbose_name_plural': 'Driver Advances',
                'ordering': ['-date_given'],
            },
        ),
        migrations.CreateModel(
            name='DriverSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=10)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partially Paid')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='management.driver')),
            ],
            options={
                'verbose_name': 'Driver Salary',
                'verbose_name_plural': 'Driver Salaries',
                'ordering': ['-period_end', 'driver'],
            },
        ),
        migrations.CreateModel(
            name='RouteCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('distance_covered', models.DecimalField(decimal_places=2, help_text='Distance in kilometers', max_digits=10)),
                ('fuel_consumed', models.DecimalField(blank=True, decimal_places=2, help_text='Fuel consumed in liters', max_digits=10, null=True)),
                ('earnings', models.DecimalField(decimal_places=2, help_text="Driver's earnings for this route", max_digits=10)),
                ('is_completed', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_completions', to='management.driver')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='management.schedule')),
            ],
            options={
                'verbose_name': 'Route Completion',
                'verbose_name_plural': 'Route Completions',
                'ordering': ['-completion_date'],
            },
        ),
    ]
