"""
Django settings for truckDriverManagement project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _

import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x_n3$z34y+@a+9x*ajqvl15aw*vcp)ws1u4lw!csrccm(@)b)b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'management',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'truckDriverManagement.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'truckDriverManagement.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

from django.urls import reverse_lazy

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'  # URL for static files in the browser

# This is where static files are collected to when you run 'collectstatic'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# This is for any static files you are manually adding to the project during development
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = '/media/'

# The filesystem path where media files will be stored
MEDIA_ROOT = BASE_DIR / 'media'
LOGIN_REDIRECT_URL = '/dashboard/'


UNFOLD = {
    "SITE_TITLE": "TMS",
    "SITE_HEADER": "Transport Management System",
    "SITE_URL": "/",
    "SITE_ICON": lambda request: static("logo.png"),
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
        },
    },
    "SHOW_BACK_BUTTON": True,
    
    "SIDEBAR": {
        "show_search": True,
        "navigation": [
            {
                "items": [
                    {
                        "title": _("Dashboard "),
                        "icon": "home",
                        "link": reverse_lazy("admin:index"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ]
            },
            {
                "title": _("User Settings"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Groups"),
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
            {
                "title": _("Management"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Dispatches"),
                        "icon": "list",
                        "link": reverse_lazy("admin:management_dispatch_changelist"),
                    },
                    {
                        "title": _("Employees"),
                        "icon": "person",
                        "link": reverse_lazy("admin:management_employee_changelist"),
                    },
                    {
                        "title": _("Truck Details"),
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:management_truckdetail_changelist"),
                    },
                    {
                        "title": _("Highway Usage"),
                        "icon": "road",
                        "link": reverse_lazy("admin:management_highwayusage_changelist"),
                    },
                    {
                        "title": _("Invoices"),
                        "icon": "receipt",
                        "link": reverse_lazy("admin:management_companyinvoice_changelist"),
                    },
                    {
                        "title": _("Payments"),
                        "icon": "credit_card",
                        "link": reverse_lazy("admin:management_payment_changelist"),
                    },
                    {
                        "title": _("Offences"),
                        "icon": "gavel",
                        "link": reverse_lazy("admin:management_offenceticket_changelist"),
                    },
                    {
                        "title": _("Maintenance"),
                        "icon": "build",
                        "link": reverse_lazy("admin:management_vehiclemaintenance_changelist"),
                    },
                    {
                        "title": _("Records"),
                        "icon": "description",
                        "link": reverse_lazy("admin:management_record_changelist"),
                    },
                ],
            },
        ],
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
